name: "Build"
on:
  push:
    branches:
      - "**"
      - "!main"
  workflow_dispatch:
    inputs:
      build:
        description: "Build & Push? (yes/no)"
        required: true
        default: "yes"

jobs:
  Conditionals:
    name: "Conditionals"
    runs-on: "ubuntu-latest"
    outputs:
      build: "${{ env.build }}"  # 'true'/'false'
    env:
      build: "false"
    steps:
      # Checkout
      - name: "Checkout"
        uses: "actions/checkout@v3"

      # Identify if files changed
      - name: "Identify changes"
        id: changed-files
        if: "${{ github.event_name != 'workflow_dispatch' }}"
        uses: "tj-actions/changed-files@b94562c2d4c1b4174b82462f4ed3a2942877032d"
        with:
          files: |
            src/**
            package.json
            .github/workflows/build.yaml

      # Set "build" output
      - name: "Set Build output (from Identify changes, if files changed)"
        if: "${{ steps.changed-files.outputs.any_changed == 'true' }}"
        run: "echo build=true >> $GITHUB_ENV"
      - name: "Set Build output (from Workflow dispatch)"
        if: "${{ github.event.inputs.build == 'yes' }}"
        run: "echo build=true >> $GITHUB_ENV"


  Build:
    name: "Build & Push"
    runs-on: "ubuntu-latest"
    needs:
      - "Conditionals"
    if: "${{ needs.Conditionals.outputs.build == 'true' }}"
    steps:
      # Checkout
      - name: "Checkout"
        uses: "actions/checkout@v3"

      # Build
      - name: "npm install"
        run: "npm install"
      - name: "npm build"
        run: "npm run build"
      - name: "npm package"
        run: "npm run package"

      # Commit & Push
      - name: "List changes"
        run: "git status"
      - name: "Commit & Push changes"
        uses: "EndBug/add-and-commit@8b817249e9bc4aac26a3dbf27ab69f410c1baf19"
        with:
          add: "."
          push: "true"
          message: "Build"
