name: "Build"
on:
  push:
    branches:
      - "develop"
  workflow_dispatch: {}

jobs:
  Build:
    name: "Build"
    runs-on: "ubuntu-latest"
    steps:
      # Checkout
      - name: "Checkout"
        uses: "actions/checkout@v3"

      # Build
      - name: "npm install"
        run: "npm install"
      - name: "npm build"
        run: "npm run build"
      - name: "npm package"
        run: "npm run package"

      # debug...
      - name: "debug changes"
        run: "git status"

