name: "Build"
on:
  push:
    branches:
      - "develop"
  workflow_dispatch:
    inputs:
      build:
        description: "Force build steps? (yes/no)"
        required: true
        default: "yes"

jobs:
  Conditionals:
    name: "Conditionals"
    runs-on: "ubuntu-latest"
    outputs:
      any-changed: "${{ steps.changed-files.outputs.any_changed }}"  # 'true'/'false'
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
      - name: "Identify changes"
        id: changed-files
        uses: "tj-actions/changed-files@b94562c2d4c1b4174b82462f4ed3a2942877032d"
        with:
          files: |
            src/**
            package.json
            .github/workflows/build.yaml

  Build:
    name: "Build & Push"
    runs-on: "ubuntu-latest"
    needs:
      - "Conditionals"
    if: "${{ needs.Conditionals.outputs.any-changed == 'true' || github.event.inputs.build == 'yes' }}"
    steps:
      # Checkout
      - name: "Checkout"
        uses: "actions/checkout@v3"

      # Build
      - name: "npm install"
        run: "npm install"
      - name: "npm build"
        run: "npm run build"
      - name: "npm package"
        run: "npm run package"

      # Commit & Push
      - name: "List changes"
        run: "git status"
      - name: "Commit & Push changes"
        uses: "EndBug/add-and-commit@8b817249e9bc4aac26a3dbf27ab69f410c1baf19"
        with:
          add: "."
          push: "true"
          message: "Build"
