name: "Test"
on:
  workflow_dispatch: {}

jobs:
  Test:
    name: "Test"
    runs-on: "ubuntu-latest"
    steps:
      - name: Run action
        uses: David-Lor/template-repository-usage-action@develop
        id: action-get
        with:
          org: "David-Lor"
          repo: "generic-template"
      - name: Print action outputs
        run: |-
          echo "Names: ${{ steps.action-get.outputs.names }}"
          echo "FullNames: ${{ steps.action-get.outputs.fullnames }}"
          echo "URLs: ${{ steps.action-get.outputs.urls }}"
          echo "JSON: ${{ steps.action-get.outputs.json }}"
